// * This function is useful for sanitizing the HTML text copied from Project Euler website
// TIP: For some reason project euler prevents numbers and other characters from being copied directly

function sanitize(string) {
  // Remove HTML tags
  const noTags = string.replace(/<[^>]*>/g, '')

  // Remove dollar signs
  const noDollarSign = noTags.replace(/\$/g, '')

  // Replace 'dots' with '...'
  const withDots = noDollarSign.replace(/dots/g, '...')

  return withDots
}

// * PUT YOUR STRING HERE ⤵
const string = `<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>`

console.log(sanitize(string))
